### PR TITLE
Add functional test

### PR DESCRIPTION
**Pull request by bvandersloot**
Now we can `go test` instead of killing any squids.

This sends 32k up and down through the DR to my own site `sendseq.benjaminvandersloot.com` and validates it.

### CODE REVIEW

**Comment by sergeyfrolov** [comment]
squid
Squid approves this PR

**Comment by sergeyfrolov** [comment]
However, wouldn't TestSendSeq be a better name for it?

**Comment by bvandersloot** [comment]
Yes, you are correct- I will rename and push.

**Comment by sergeyfrolov** [comment]
Thank you very much for this contribution!

**Pull request merged**
